version: '3'

services:
  comp110devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
